config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "home/info"
  get "home/insertdata"
  get "home/showdata"

  resources :anmeldungs

  resources :kundes

  root 'home#index'

end

app/models/anmeldung.rb
class Anmeldung < ActiveRecord::Base
	belongs_to :kunde

	validates :identnummer, :fz_brief_nr, :amtliches_kennzeichen1, :amtliches_kennzeichen2, :neues_kennzeichen1, :neues_kennzeichen2, presence: true
	validates :evb_nr, :kunde_id, presence: true
	validates_inclusion_of :feinstaubplakette, :versand_art,:in => [true, false]


end

app/models/kunde.rb
class Kunde < ActiveRecord::Base
	has_many :anmeldungs
	validates :gruppe, :anrede, :nachname, :vorname, :geburtsdatum, :geburtsort, :adresse, :plz, :stadt, presence: true
	validates_inclusion_of :tsp_versicherungskunde, :in => [true, false]
	validates_length_of :plz, :maximum => 5


	def full_name
    "ID: " + self.id.to_s + ". " + self.nachname + ", " + self.vorname
  end
  
end

app/controllers/anmeldungs_controller.rb
class AnmeldungsController < ApplicationController
  before_action :set_anmeldung, only: [:show, :edit, :update, :destroy]

  # GET /anmeldungs
  # GET /anmeldungs.json
  def index
    @anmeldungs = Anmeldung.all
  end

  # GET /anmeldungs/1
  # GET /anmeldungs/1.json
  def show
  end

  # GET /anmeldungs/new
  def new
    @anmeldung = Anmeldung.new
  end

  # GET /anmeldungs/1/edit
  def edit
  end

  # POST /anmeldungs
  # POST /anmeldungs.json
  def create
    @anmeldung = Anmeldung.new(anmeldung_params)

    respond_to do |format|
      if @anmeldung.save
        format.html { redirect_to @anmeldung, notice: 'Anmeldung was successfully created.' }
        format.json { render :show, status: :created, location: @anmeldung }
      else
        format.html { render :new }
        format.json { render json: @anmeldung.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anmeldungs/1
  # PATCH/PUT /anmeldungs/1.json
  def update
    respond_to do |format|
      if @anmeldung.update(anmeldung_params)
        format.html { redirect_to @anmeldung, notice: 'Anmeldung was successfully updated.' }
        format.json { render :show, status: :ok, location: @anmeldung }
      else
        format.html { render :edit }
        format.json { render json: @anmeldung.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anmeldungs/1
  # DELETE /anmeldungs/1.json
  def destroy
    @anmeldung.destroy
    respond_to do |format|
      format.html { redirect_to anmeldungs_url, notice: 'Anmeldung was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anmeldung
      @anmeldung = Anmeldung.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anmeldung_params
      params.require(:anmeldung).permit(:identnummer, :fz_brief_nr, :amtliches_kennzeichen1, :amtliches_kennzeichen2, :neues_kennzeichen1, :neues_kennzeichen2, :feinstaubplakette, :saison_von, :saison_bis, :evb_nr, :kva_notiz, :tsp_notiz, :versand_art, :kunde_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  end

  def info
  end

	def insertdata
  end

  def showdata
  end

end

app/controllers/kundes_controller.rb
class KundesController < ApplicationController
  before_action :set_kunde, only: [:show, :edit, :update, :destroy]

  # GET /kundes
  # GET /kundes.json
  def index
   # @kundes = Kunde.all
    @search = Kunde.search(params[:q])
    @kundes = @search.result
    @search.build_condition 
  end

  # GET /kundes/1
  # GET /kundes/1.json
  def show
  end

  # GET /kundes/new
  def new
    @kunde = Kunde.new
  end

  # GET /kundes/1/edit
  def edit
  end

  # POST /kundes
  # POST /kundes.json
  def create
    @kunde = Kunde.new(kunde_params)

    respond_to do |format|
      if @kunde.save
        format.html { redirect_to @kunde, notice: 'Kunde was successfully created.' }
        format.json { render :show, status: :created, location: @kunde }
      else
        format.html { render :new }
        format.json { render json: @kunde.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kundes/1
  # PATCH/PUT /kundes/1.json
  def update
    respond_to do |format|
      if @kunde.update(kunde_params)
        format.html { redirect_to @kunde, notice: 'Kunde was successfully updated.' }
        format.json { render :show, status: :ok, location: @kunde }
      else
        format.html { render :edit }
        format.json { render json: @kunde.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kundes/1
  # DELETE /kundes/1.json
  def destroy
    @kunde.destroy
    respond_to do |format|
      format.html { redirect_to kundes_url, notice: 'Kunde was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kunde
      @kunde = Kunde.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kunde_params
      params.require(:kunde).permit(:gruppe, :anrede, :nachname, :geburtsname, :vorname, :geburtsdatum, :geburtsort, :adresse, :plz, :stadt, :telefonnummer, :tsp_versicherungskunde)
    end
end

app/helpers/anmeldungs_helper.rb
module AnmeldungsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kundes_helper.rb
module KundesHelper
end

app/views/anmeldungs/_form.html.erb
<%= form_for(@anmeldung) do |f| %>
  <% if @anmeldung.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anmeldung.errors.count, "error") %> prohibited this anmeldung from being saved:</h2>

      <ul>
      <% @anmeldung.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="well">          
  <div class="panel panel-info">
    <div class="panel-body">

      <div class="form-group">
        <%= f.label :kunde_id %><br>
        <%= f.select :kunde_id, Kunde.all.collect {|c| [ c.full_name, c.id ] }, { :include_blank => true, :selected => @anmeldung.kunde_id, :prompt => "bitte Kunde wählen für den der Antrag erstellt wird"}, class: "form-control" %>
      </div> 

      <div class="col-md-6" id="leftCol">
        <div class="well">    
          <div class="form-group">
            <%= f.label :identnummer %><br>
            <%= f.text_field :identnummer %>
          </div>
          <div class="form-group">
            <%= f.label :fz_brief_nr %><br>
            <%= f.text_field :fz_brief_nr %>
          </div>
          <div class="form-group">
            <%= f.label "amtliches Kennzeichen" %><br>
            <%= f.text_field :amtliches_kennzeichen1, placeholder: 'Ort', :maxlength => 3, :size => 3 %> - <%= f.text_field :amtliches_kennzeichen2, placeholder: 'Kennung'  %>
          </div>
          <div class="form-group">
            <%= f.label "neues_kennzeichen" %><br>
            <%= f.text_field :neues_kennzeichen1, placeholder: 'Ort', :maxlength => 3, :size => 3  %> - <%= f.text_field :neues_kennzeichen2, placeholder: 'Kennung'  %>
          </div>    
        </div>
      </div>

      <div class="col-md-6" id="leftCol">
        <div class="well">  
          <div class="form-group">
            <%= f.label :feinstaubplakette %><br>
            <%= f.radio_button :feinstaubplakette, :true  %> <%= f.label :feinstaubplakette, "Ja" %>
            <%= f.radio_button :feinstaubplakette, :false  %> <%= f.label :feinstaubplakette, "Nein" %>
          </div>          
          <div class="form-group">
            <%= f.label :saison_von %><br>
            <%= f.date_select :saison_von, {:use_month_names => ['Jan', 'Feb', 'März', 'Apr', 'Mai', 'Juni', 'Juli', 'Aug', 'Sep', 'Okt', 'Nov','Dez'], :discard_year => true, :include_blank => true, :default => nil} %>
          </div>
          <div class="form-group">
            <%= f.label :saison_bis %><br>
            <%= f.date_select :saison_bis, {:use_month_names => ['Jan', 'Feb', 'März', 'Apr', 'Mai', 'Juni', 'Juli', 'Aug', 'Sep', 'Okt', 'Nov','Dez'], :discard_year => true, :include_blank => true, :default => nil} %>
          </div>
          <div class="form-group">
            <%= f.label :evb_nr %><br>
            <%= f.text_field :evb_nr %>
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <div class="well"> 
          <div class="form-group">
            <%= f.label :kva_notiz %><br>
            <%= f.text_area :kva_notiz, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :tsp_notiz %><br>
            <%= f.text_area :tsp_notiz, class: "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :versand_art %><br>
            <%= f.radio_button :versand_art, :true  %> <%= f.label :versand_art, "Lieferung" %>
            <%= f.radio_button :versand_art, :false  %> <%= f.label :versand_art, "Abholung" %>
          </div> 
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Save Result', class: "btn btn-success" %> | | 
    <%= link_to 'Cancel', anmeldungs_path, class: "btn btn-danger" %>
  </div>
  <% end %>
</div>

app/views/anmeldungs/edit.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>KFZ Zulassungsdaten ändern</h1>
      </div>

		  <div class="col-md-3" id="leftCol">
		  	<div class="well">  	
			    <%= render 'layouts/sidebar_insert' %>
				</div>
	    </div>		 

		  <div class="col-md-9" id="rightCol">		  		
				<%= render 'form' %>	
			</div>


		</div>		 
  </div>
</div>

<%= link_to 'Show', @anmeldung %> |
<%= link_to 'Back', anmeldungs_path %>

app/views/anmeldungs/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>Alle Zulassungsanträge</h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          <%= render 'layouts/sidebar_show' %>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol">          
        <div class="well">          
          <div class="panel panel-info">
            <div class="panel-body">  
              <div class="bs-example table-responsive">
                <table class="table table-striped table-bordered table-hover ">
                <thead>
                  <tr>
                    <th>Kunde</th>
                    <th>Identnummer</th>
                    <th>Fz-brief-nr</th>
                    <th>Amtliches kennzeichen</th>
                    <th>Neues kennzeichen</th>
                  </tr>
                </thead>

                <tbody>
                  <% @anmeldungs.each do |anmeldung| %>
                    <tr>
                      <td><%= link_to anmeldung.kunde.vorname, anmeldung_path(anmeldung) %>, <%= link_to anmeldung.kunde.nachname, anmeldung_path(anmeldung) %></td>
                      <td><%= anmeldung.identnummer %></td>
                      <td><%= anmeldung.fz_brief_nr %></td>
                      <td><%= anmeldung.amtliches_kennzeichen1 %> - <%= anmeldung.amtliches_kennzeichen2 %></td>
                      <td><%= anmeldung.neues_kennzeichen1 %> - <%= anmeldung.neues_kennzeichen2 %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              </div>

<br>
            </div>
          </div>
        </div>    
      </div>


    </div>     
  </div>
</div>



<%= link_to 'New Anmeldung', new_anmeldung_path %>

app/views/anmeldungs/new.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>KFZ Zulassungsantrag erstellen</h1>
      </div>

		  <div class="col-md-3" id="leftCol">
		  	<div class="well">  	
			    <%= render 'layouts/sidebar_insert' %>
				</div>
	    </div>		 

		  <div class="col-md-9" id="rightCol">		  		
				<%= render 'form' %>	
			</div>


		</div>		 
  </div>
</div>

app/views/anmeldungs/show.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>KFZ Anmeldung für <%= @anmeldung.kunde.vorname %> <%= @anmeldung.kunde.nachname %> </h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          <%= render 'layouts/sidebar_show' %>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol">          
        <div class="well">          
          <div class="panel panel-info">
            <div class="panel-body">  

              <div id="box">   
                <p><strong>
                  <%= @anmeldung.neues_kennzeichen1 %> - <%= @anmeldung.neues_kennzeichen2 %> 
                </strong></p>

                <p><strong>
                  <%= @anmeldung.amtliches_kennzeichen1 %> - <%= @anmeldung.amtliches_kennzeichen2 %> 
                </strong></p>  
                
                <p><br></p>

                <p><strong>
                  <%= @anmeldung.kunde.anrede %>
                </strong></p>  

                <p><strong>
                  <%= @anmeldung.kunde.nachname %>
                </strong></p>  

                <p><strong>
                  <%= @anmeldung.kunde.geburtsname %>
                </strong></p>              

                <p><strong>
                  <%= @anmeldung.kunde.vorname %>
                </strong></p>
               
                <p><strong>
                  <%= @anmeldung.kunde.geburtsdatum %>
                </strong></p>

                <p><strong>
                  <%= @anmeldung.kunde.geburtsort %>
                </strong></p>

                <p><strong>
                  <%= @anmeldung.kunde.plz %> <%= @anmeldung.kunde.stadt %>
                </strong></p>

                <p><strong>
                  <%= @anmeldung.kunde.adresse %>
                </strong></p>

                <p><strong>
                  <br>
                </strong></p>

                <p><strong>
                  tsp GmbH 
                </strong></p>

                <p><strong>
                  Versicherungs- und Zulassungsservice
                </strong></p>

                <p><strong>
                  Tel.: 030 398 375 80
                </strong></p>

                <p><strong>
                  10551 Berlin
                </strong></p>

                <p><strong>
                  Turmstr. 39 
                </strong></p>

                <p><strong>
                  <br>
                </strong></p>

                <p><strong>
                  <%= @anmeldung.identnummer %>
                </strong></p>

                <p><strong>
                  <%= @anmeldung.fz_brief_nr %>
                </strong></p>

                <p><strong>
                  <br> 
                </strong></p>

                <p><strong>
                  <br> 
                </strong></p>


                <p><strong>
                  <%= @anmeldung.evb_nr %>
                </strong></p>
              </div> 
              <div id="boxfsp"> 
                 <p><strong>
                  <% if @anmeldung.feinstaubplakette == true %>
                      <p >X</p>                    
                    <% else %>
                      <p> </p>
                    <% end %>
                </strong></p>
              </div>

              <div id="boxsv"> 
                 <p><strong>
                  <%= @anmeldung.saison_von.to_formatted_s(:short) if @anmeldung.saison_von %>
                </strong></p>
              </div>

              <div id="boxsb"> 
                 <p><strong>
                  <%= @anmeldung.saison_bis.to_formatted_s(:short) if @anmeldung.saison_bis %>
                </strong></p>
              </div>

              <%= image_tag ("zulassungsantrag1.png") %>
            </div>
          </div>
        </div>    
      </div>


    </div>     
  </div>
</div> 





<%= link_to 'Edit', edit_anmeldung_path(@anmeldung) %> |
<%= link_to 'Back', anmeldungs_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/kundes/_form.html.erb
<%= form_for(@kunde) do |f| %>
  <% if @kunde.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kunde.errors.count, "error") %> prohibited this kunde from being saved:</h2>

      <ul>
      <% @kunde.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="well">          
  <div class="panel panel-info">
    <div class="panel-body">

      <div class="col-md-6" id="leftCol">
        <div class="well">    
          <div class="form-group">
            <%= f.label :gruppe %><br>
            <%= f.radio_button :gruppe, "Firma"  %> <%= f.label :gruppe, "Firma" %>
            <%= f.radio_button :gruppe, "Privatperson"  %> <%= f.label :gruppe, "Privatperson" %>
          </div>

          <div class="form-group">
            <%= f.label :tsp_versicherungskunde %><br>
            <%= f.radio_button :tsp_versicherungskunde, :true  %> <%= f.label :tsp_versicherungskunde, "Ja" %>
            <%= f.radio_button :tsp_versicherungskunde, :false  %> <%= f.label :tsp_versicherungskunde, "Nein" %>
          </div>
          <div class="form-group">
            <%= f.label :anrede %><br>
            <%= f.radio_button :anrede, "Frau"  %> <%= f.label :anrede, "Frau" %>
            <%= f.radio_button :anrede, "Herr"  %> <%= f.label :anrede, "Herr" %>
          </div>          
          <div class="form-group">
            <%= f.label :nachname %><br>
            <%= f.text_field :nachname %>
          </div>
          <div class="form-group">
            <%= f.label :geburtsname %><br>
            <%= f.text_field :geburtsname %>
          </div>
          <div class="form-group">
            <%= f.label :vorname %><br>
            <%= f.text_field :vorname %>
          </div>
        </div>
      </div>

      <div class="col-md-6" id="rightCol">
        <div class="well"> 
          <div class="form-group">
            <%= f.label :geburtsdatum %><br>
            <%= f.date_select :geburtsdatum, {:start_year => Date.today.year - 70, :end_year => Date.today.year - 15,:prompt => { :day => 'Tag', :month => 'Monat', :year => 'Jahr' }} %>
          </div>
          <div class="form-group">
            <%= f.label :geburtsort %><br>
            <%= f.text_field :geburtsort %>
          </div>
          <div class="form-group">
            <%= f.label :adresse %><br>
            <%= f.text_field :adresse %>
          </div>
          <div class="form-group">
            <%= f.label :plz %><br>
            <%= f.text_field :plz %>
          </div>
          <div class="form-group">
            <%= f.label :stadt %><br>
            <%= f.text_field :stadt %>
          </div>
          <div class="form-group">
            <%= f.label :telefonnummer %><br>
            <%= f.text_field :telefonnummer %>
          </div>
        </div>
      </div>

    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Speichern', class: "btn btn-success" %> | | 
    <%= link_to 'Löschen', kundes_path, class: "btn btn-danger" %>
  </div>
  <% end %>
</div>

app/views/kundes/_tablekunden.html.erb
<div class="table-responsive table-scrollable">
  <table class="table table-striped table-bordered table-hover ">
    <thead>
      <tr>
        <th>Gruppe</th>
        <th>Anrede</th>
        <th>Nachname</th>
        <th>Geburtsname</th>
        <th>Vorname</th>
        <th>Geburtsdatum</th>
        <th>Geburtsort</th>
        <th>Adresse</th>
        <th>Plz</th>
        <th>Stadt</th>
        <th>Telefonnummer</th>
        <th>Tsp versicherungskunde</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @kundes.each do |kunde| %>
        <tr>
          <td><%= kunde.gruppe %></td>
          <td><%= kunde.anrede %></td>
          <td><%= link_to kunde.nachname, kunde_path(kunde) %></td>
          <td><%= kunde.geburtsname %></td>
          <td><%= link_to kunde.vorname, kunde_path(kunde) %></td>
          <td><%= kunde.geburtsdatum %></td>
          <td><%= kunde.geburtsort %></td>
          <td><%= kunde.adresse %></td>
          <td><%= kunde.plz %></td>
          <td><%= kunde.stadt %></td>
          <td><%= kunde.telefonnummer %></td>
          <td><%= kunde.tsp_versicherungskunde %></td>
          <td><%= link_to 'Show', kunde, class: "btn btn-info btn-sm"  %></td>
          <td><%= link_to 'Edit', edit_kunde_path(kunde), class: "btn btn-warning btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/kundes/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>Kunden Liste<br>

          <small><%= pluralize(@kundes.count, "Kunde") %></small></h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          <%= render 'layouts/sidebar_show' %>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 


        <div class="well">
          Suche mit verschiedene Filteroptionen
          <%= search_form_for @search do |f| %>
          <%= f.condition_fields do |c| %>
            <div class="field">
              <%= c.attribute_fields do |a| %>
                <%= a.attribute_select  %>
              <% end %>
              <%= c.predicate_select %>
              <%= c.value_fields do |v| %>
                <%= v.text_field :value %>
              <% end %>
              </div>
            <% end %>
            <div class="actions"><%= f.submit "Search", class: "btn-sm btn-success"  %> | 
            <%= link_to 'alle Kunden Anzeigen', kundes_path, class: "btn-sm btn-info" %> </div>
          <% end %>
        </div>

        <%= link_to 'Neuer Kunde anlegen', new_kunde_path, class: "btn btn-success " %> 

        <%= render 'tablekunden' %> <br>
      </div>

    </div>
  </div>
</div>

app/views/kundes/show.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">


      <div class="page-header">          
        <h1>
          Kunde <%= @kunde.anrede if @kunde.anrede %> <%= @kunde.vorname if @kunde.vorname %> <%= @kunde.nachname if @kunde.nachname %>
        </h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          <%= render 'layouts/sidebar_show' %>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well">      
        <%= link_to 'KFZ Anmeldung', new_anmeldung_path, class: "btn btn-success" %> <br/>

          <div class="panel panel-info">
            <div class="panel-body"> 

              <div class="col-md-6" id="leftCol">
                <div class="well">  
                  <p>
                    <strong>Gruppe:</strong>
                    <%= @kunde.gruppe %>
                  </p>

                  <p>
                    <strong>Tsp versicherungskunde:</strong>
                    <%= @kunde.tsp_versicherungskunde %>
                  </p>

                  <p>
                    <strong>Anrede:</strong>
                    <%= @kunde.anrede %>
                  </p>

                  <p>
                    <strong>Nachname:</strong>
                    <%= @kunde.nachname %>
                  </p>

                  <p>
                    <strong>Geburtsname:</strong>
                    <%= @kunde.geburtsname %>
                  </p>

                  <p>
                    <strong>Vorname:</strong>
                    <%= @kunde.vorname %>
                  </p>
                </div>
              </div> 

              <div class="col-md-6" id="rightCol">
                <div class="well">  
                  <p>
                    <strong>Geburtsdatum:</strong>
                    <%= @kunde.geburtsdatum %>
                  </p>

                  <p>
                    <strong>Geburtsort:</strong>
                    <%= @kunde.geburtsort %>
                  </p>

                  <p>
                    <strong>Adresse:</strong>
                    <%= @kunde.adresse %>
                  </p>

                  <p>
                    <strong>Plz:</strong>
                    <%= @kunde.plz %>
                  </p>

                  <p>
                    <strong>Stadt:</strong>
                    <%= @kunde.stadt %>
                  </p>

                  <p>
                    <strong>Telefonnummer:</strong>
                    <%= @kunde.telefonnummer %>
                  </p>                  
                </div>
              </div>              
            </div>
          </div>  
   
          <%= link_to 'Kundendaten ändern', edit_kunde_path(@kunde), class: "btn btn-warning btn-sm" %> |  | 
          <%= link_to 'Löschen', @kunde, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Sind Sie sicher?' } %> | 
          <%= link_to 'Alle Kunden anzeigen', kundes_path , class: "btn btn-info btn-sm" %> 
                 
        </div>
      </div>

    </div>     
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="link"><%= link_to image_tag("logo.jpg", alt: "TSP Logo"),root_path%></li>
        <li class="link"><%= link_to "Info", home_info_path %></li>
        <li class="link"><%= link_to "Dateneingabe", home_insertdata_path %></li>
        <li class="link"><%= link_to "Datenausgabe",  home_showdata_path %></li>
      </ul>
    </div>

  </div>
</div>


app/views/layouts/_sidebar_insert.html.erb
<h3>Insert</h3> 
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Stammdaten</h3>
  </div>
  <div class="panel-body"> 
    <ul class="nav nav-sidebar">
      <li ><%= link_to "Kunde anlegen", new_kunde_path %></li>
		</ul>
	</div> 
</div> 

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Anwendungen</h3>
  </div>
  <div class="panel-body"> 
    <ul class="nav nav-sidebar">
			<li class="active"><%= link_to "KFZ Zulassung",  new_anmeldung_path  %></li>
	</div> 
</div>








app/views/layouts/_sidebar_show.html.erb
<h3>Insert</h3> 
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Stammdaten</h3>
  </div>
  <div class="panel-body"> 
    <ul class="nav nav-sidebar">
      <li ><%= link_to "Kunden anzeigen",  kundes_path %></li>
		</ul>
	</div> 
</div> 

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Anwendungen</h3>
  </div>
  <div class="panel-body"> 
    <ul class="nav nav-sidebar">
			<li class="active"><%= link_to "KFZ Zulassung",  anmeldungs_path  %></li>
	</div> 
</div>






